#!/usr/bin/env node
import fg from "fast-glob";
import fs from "node:fs";
import path from "node:path";

const CWD = process.cwd(); // app root (hn-demo)
const toPosix = (p: string) => p.split(path.sep).join("/");

function toRoute(fileRelFromProject: string) {
  // fileRelFromProject e.g. "src/pages/about.page.tsx"
  let r =
    "/" +
    toPosix(fileRelFromProject)
      .replace(/^src\/pages\//, "")
      .replace(/\/index\.page\.(t|j)sx?$/, "")
      .replace(/\.page\.(t|j)sx?$/, "");
  if (r === "" || r === "/index") r = "/";
  return r;
}

async function main() {
  const projectRoot = CWD;

  // Discover pages relative to the project (hn-demo) root
  const files = await fg("src/pages/**/*.page.{tsx,ts,jsx,js}", {
    cwd: projectRoot,
    onlyFiles: true,
    dot: false,
  });
  files.sort();

  const outDir = path.join(projectRoot, "src/.dex");
  const outFile = path.join(outDir, "routes.gen.ts");
  fs.mkdirSync(outDir, { recursive: true });

  // Build lines for the generated TS
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED — DO NOT EDIT");
  lines.push("// Generated by dex-routes CLI");
  lines.push(
    "export type Loader = () => Promise<{ default: any; ssr?: boolean }>; // minimal type"
  );
  lines.push("export const ROUTE_LOADERS: Record<string, Loader> = {");

  for (const relFromProject of files) {
    const route = toRoute(relFromProject);

    // Absolute path to the page file
    const absPage = path.join(projectRoot, relFromProject);

    // Compute import path RELATIVE TO src/.dex/ (where routes.gen.ts lives)
    const relFromDexDir = path.relative(outDir, absPage); // e.g. "../pages/about.page.tsx"
    const importPathRaw = relFromDexDir.startsWith(".")
      ? relFromDexDir
      : `./${relFromDexDir}`;
    //    const importPath = toPosix(importPathRaw);
    const importPath = toPosix(importPathRaw.replace(/\.(t|j)sx?$/, ""));

    lines.push(
      `  ${JSON.stringify(route)}: () => import(${JSON.stringify(importPath)}),`
    );
  }

  lines.push("};");
  lines.push("");
  lines.push(
    "export const ROUTES_LIST: string[] = Object.keys(ROUTE_LOADERS);"
  );

  fs.writeFileSync(outFile, lines.join("\n") + "\n", "utf8");

  console.log(
    `[dex-routes] wrote ${files.length} route(s) to ${path.relative(
      projectRoot,
      outFile
    )}`
  );
  for (const rel of files) {
    const abs = path.join(projectRoot, rel);
    const relFromDex = path.relative(outDir, abs);
    console.log(`  ${toRoute(rel)} <- ${toPosix(relFromDex)}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
