// AUTO-GENERATED — DO NOT EDIT
// Generated by dex-routes CLI
export type Loader = () => Promise<{ default: any; ssr?: boolean }>; // minimal type
export const ROUTE_LOADERS: Record<string, Loader> = {
  "/about": () => import("../pages/about.page"),
  "/": () => import("../pages/index.page"),
};

export const ROUTES_LIST: string[] = Object.keys(ROUTE_LOADERS);
